// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// QuotaService is an autogenerated mock type for the QuotaService type
type QuotaService struct {
	mock.Mock
}

// GetQuotaToken provides a mock function with given fields: ownerID
func (_m *QuotaService) GetQuotaToken(ownerID string) (uuid.UUID, error) {
	ret := _m.Called(ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotaToken")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return rf(ownerID)
	}
	if rf, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = rf(ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReturnQuotaToken provides a mock function with given fields: token
func (_m *QuotaService) ReturnQuotaToken(token uuid.UUID) {
	_m.Called(token)
}

// NewQuotaService creates a new instance of QuotaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuotaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuotaService {
	mock := &QuotaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
